[plugin]
preloaders = [
  # Do not preload MTP mount_point, cause they are very slow.
  # Environment variable won't work here.
  # Using absolute path instead.
  { name = "/home/erhan/Media/**/*", run = "noop" },
  #... the rest of preloaders
]
previewers = [
  # Allow to preview folder.
  { name = "*/", run = "folder", sync = true },
  { mime = "image/*", run = "image"},
  # Do not preview MTP mount_point (uncomment to except text file)
  #  { mime = "{text/*,application/x-subrip}", run = "code" },
  # Using absolute path.
  { name = "/home/erhan/Media/**/*", run = "noop" },
  #... the rest of previewers
]
